// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/rpc/cluster.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	lib/rpc/cluster.proto
	lib/rpc/session.proto

It has these top-level messages:
	ServiceInfo
	ServerInfo
	ServerInfoIDMap
	RegisterReturn
	UserInfo
	ClientInfo
	Session
	SessionRequest
	SessionResult
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
}

func (m *ServiceInfo) Reset()                    { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string            { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()               {}
func (*ServiceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ServerInfo struct {
	Type     string         `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	ID       uint32         `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	IP       string         `protobuf:"bytes,3,opt,name=IP" json:"IP,omitempty"`
	Port     int32          `protobuf:"varint,4,opt,name=Port" json:"Port,omitempty"`
	Services []*ServiceInfo `protobuf:"bytes,5,rep,name=Services" json:"Services,omitempty"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerInfo) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ServerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServerInfoIDMap struct {
	Servers map[uint32]*ServerInfo `protobuf:"bytes,1,rep,name=Servers" json:"Servers,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServerInfoIDMap) Reset()                    { *m = ServerInfoIDMap{} }
func (m *ServerInfoIDMap) String() string            { return proto.CompactTextString(m) }
func (*ServerInfoIDMap) ProtoMessage()               {}
func (*ServerInfoIDMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerInfoIDMap) GetServers() map[uint32]*ServerInfo {
	if m != nil {
		return m.Servers
	}
	return nil
}

type RegisterReturn struct {
	ID          uint32                      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NewServers  map[string]*ServerInfoIDMap `protobuf:"bytes,2,rep,name=NewServers" json:"NewServers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DownServers map[string]*ServerInfoIDMap `protobuf:"bytes,3,rep,name=DownServers" json:"DownServers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RegisterReturn) Reset()                    { *m = RegisterReturn{} }
func (m *RegisterReturn) String() string            { return proto.CompactTextString(m) }
func (*RegisterReturn) ProtoMessage()               {}
func (*RegisterReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterReturn) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RegisterReturn) GetNewServers() map[string]*ServerInfoIDMap {
	if m != nil {
		return m.NewServers
	}
	return nil
}

func (m *RegisterReturn) GetDownServers() map[string]*ServerInfoIDMap {
	if m != nil {
		return m.DownServers
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceInfo)(nil), "rpc.ServiceInfo")
	proto.RegisterType((*ServerInfo)(nil), "rpc.ServerInfo")
	proto.RegisterType((*ServerInfoIDMap)(nil), "rpc.ServerInfoIDMap")
	proto.RegisterType((*RegisterReturn)(nil), "rpc.RegisterReturn")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (Cluster_RegisterClient, error)
	Sync(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*RegisterReturn, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Register(ctx context.Context, opts ...grpc.CallOption) (Cluster_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cluster_serviceDesc.Streams[0], c.cc, "/rpc.Cluster/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterRegisterClient{stream}
	return x, nil
}

type Cluster_RegisterClient interface {
	Send(*ServerInfo) error
	Recv() (*RegisterReturn, error)
	grpc.ClientStream
}

type clusterRegisterClient struct {
	grpc.ClientStream
}

func (x *clusterRegisterClient) Send(m *ServerInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterRegisterClient) Recv() (*RegisterReturn, error) {
	m := new(RegisterReturn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) Sync(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*RegisterReturn, error) {
	out := new(RegisterReturn)
	err := grpc.Invoke(ctx, "/rpc.Cluster/Sync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	Register(Cluster_RegisterServer) error
	Sync(context.Context, *ServerInfo) (*RegisterReturn, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Register(&clusterRegisterServer{stream})
}

type Cluster_RegisterServer interface {
	Send(*RegisterReturn) error
	Recv() (*ServerInfo, error)
	grpc.ServerStream
}

type clusterRegisterServer struct {
	grpc.ServerStream
}

func (x *clusterRegisterServer) Send(m *RegisterReturn) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterRegisterServer) Recv() (*ServerInfo, error) {
	m := new(ServerInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cluster_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cluster/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Sync(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Cluster_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Cluster_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lib/rpc/cluster.proto",
}

func init() { proto.RegisterFile("lib/rpc/cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x4a, 0xfb, 0x40,
	0x18, 0xfc, 0x6d, 0xd2, 0xfe, 0xda, 0x7e, 0xb1, 0x7f, 0x58, 0x15, 0x96, 0x9c, 0x6a, 0x54, 0x08,
	0x22, 0xa9, 0x54, 0x10, 0xb1, 0xc7, 0x46, 0x21, 0x88, 0xa5, 0x6c, 0x8b, 0xf7, 0x36, 0xac, 0x12,
	0xac, 0x49, 0xdc, 0xa4, 0x2d, 0xb9, 0xfa, 0x1a, 0xbe, 0x98, 0x8f, 0x23, 0xd9, 0x34, 0xe9, 0x36,
	0xf4, 0x20, 0x78, 0xfb, 0xbe, 0xec, 0xcc, 0xec, 0xcc, 0x24, 0x81, 0xe3, 0x85, 0x37, 0xef, 0xf1,
	0xd0, 0xed, 0xb9, 0x8b, 0x65, 0x14, 0x33, 0x6e, 0x85, 0x3c, 0x88, 0x03, 0xac, 0xf2, 0xd0, 0x35,
	0x06, 0xa0, 0x4d, 0x18, 0x5f, 0x79, 0x2e, 0x73, 0xfc, 0x97, 0x00, 0x63, 0xa8, 0x8c, 0x66, 0xef,
	0x8c, 0xa0, 0x2e, 0x32, 0x1b, 0x54, 0xcc, 0x98, 0x40, 0xed, 0x99, 0xf1, 0xc8, 0x0b, 0x7c, 0xa2,
	0x74, 0x91, 0x59, 0xa5, 0xf9, 0x6a, 0x7c, 0x22, 0x80, 0x94, 0xcd, 0x78, 0x4e, 0x9e, 0x26, 0x61,
	0x41, 0x4e, 0x67, 0xdc, 0x02, 0xc5, 0xb1, 0x05, 0xaf, 0x49, 0x15, 0xc7, 0x16, 0xfb, 0x98, 0xa8,
	0x02, 0xa1, 0x38, 0xe3, 0x94, 0x33, 0x0e, 0x78, 0x4c, 0x2a, 0x42, 0x59, 0xcc, 0xf8, 0x12, 0xea,
	0x1b, 0x4f, 0x11, 0xa9, 0x76, 0x55, 0x53, 0xeb, 0x77, 0x2c, 0x1e, 0xba, 0x96, 0x64, 0x94, 0x16,
	0x08, 0xe3, 0x0b, 0x41, 0x7b, 0x6b, 0xc2, 0xb1, 0x9f, 0x66, 0x21, 0x1e, 0x40, 0x2d, 0x7b, 0x14,
	0x11, 0x24, 0x04, 0x4e, 0x0a, 0x01, 0x09, 0xb6, 0xd9, 0xa3, 0x7b, 0x3f, 0xe6, 0x09, 0xcd, 0x19,
	0xfa, 0x23, 0x1c, 0xc8, 0x07, 0xb8, 0x03, 0xea, 0x1b, 0x4b, 0x44, 0xaa, 0x26, 0x4d, 0x47, 0x7c,
	0x0e, 0xd5, 0xd5, 0x6c, 0xb1, 0x64, 0x22, 0x97, 0xd6, 0x6f, 0x97, 0xc4, 0x69, 0x76, 0x7a, 0xa7,
	0xdc, 0x22, 0xe3, 0x5b, 0x81, 0x16, 0x65, 0xaf, 0x5e, 0xda, 0x3b, 0x65, 0xf1, 0x92, 0xfb, 0x9b,
	0x4a, 0x50, 0x51, 0xc9, 0x10, 0x60, 0xc4, 0xd6, 0xb9, 0x5f, 0x45, 0xf8, 0x3d, 0x15, 0x92, 0xbb,
	0x44, 0x6b, 0x8b, 0xca, 0x1c, 0x4b, 0x34, 0xfc, 0x00, 0x9a, 0x1d, 0xac, 0xfd, 0x5c, 0x45, 0x15,
	0x2a, 0x67, 0xfb, 0x54, 0x24, 0x58, 0x26, 0x23, 0x13, 0xf5, 0x09, 0xb4, 0x4b, 0xd7, 0xc8, 0xf9,
	0x1b, 0x59, 0xfe, 0x8b, 0xdd, 0xfc, 0x47, 0xfb, 0xca, 0x95, 0x4a, 0xd0, 0xa7, 0xd0, 0x29, 0xdf,
	0xfa, 0x77, 0xd5, 0xfe, 0x07, 0xd4, 0x86, 0xd9, 0x07, 0x8d, 0x6f, 0xa0, 0x9e, 0xa7, 0xc4, 0xe5,
	0xb7, 0xa1, 0x1f, 0xee, 0x69, 0xc1, 0xf8, 0x67, 0xa2, 0x2b, 0x84, 0x2d, 0xa8, 0x4c, 0x12, 0xdf,
	0xfd, 0x2d, 0x67, 0xfe, 0x5f, 0xfc, 0x39, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0x66,
	0x17, 0x28, 0x52, 0x03, 0x00, 0x00,
}
