// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/rpc/session.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserInfo struct {
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Domain    string `protobuf:"bytes,2,opt,name=Domain" json:"Domain,omitempty"`
	Device    string `protobuf:"bytes,3,opt,name=Device" json:"Device,omitempty"`
	NickName  string `protobuf:"bytes,4,opt,name=NickName" json:"NickName,omitempty"`
	LoginTime uint64 `protobuf:"varint,5,opt,name=LoginTime" json:"LoginTime,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UserInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetLoginTime() uint64 {
	if m != nil {
		return m.LoginTime
	}
	return 0
}

type ClientInfo struct {
	Extra         map[string]string `protobuf:"bytes,1,rep,name=Extra" json:"Extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientType    uint32            `protobuf:"varint,2,opt,name=ClientType" json:"ClientType,omitempty"`
	ClientVersion string            `protobuf:"bytes,3,opt,name=ClientVersion" json:"ClientVersion,omitempty"`
	ProtoType     string            `protobuf:"bytes,4,opt,name=ProtoType" json:"ProtoType,omitempty"`
	ProtoVersion  string            `protobuf:"bytes,5,opt,name=ProtoVersion" json:"ProtoVersion,omitempty"`
	OSType        uint32            `protobuf:"varint,6,opt,name=OSType" json:"OSType,omitempty"`
	OSVersion     string            `protobuf:"bytes,7,opt,name=OSVersion" json:"OSVersion,omitempty"`
	DeviceType    string            `protobuf:"bytes,8,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceNumber  string            `protobuf:"bytes,9,opt,name=DeviceNumber" json:"DeviceNumber,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ClientInfo) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *ClientInfo) GetClientType() uint32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

func (m *ClientInfo) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *ClientInfo) GetProtoType() string {
	if m != nil {
		return m.ProtoType
	}
	return ""
}

func (m *ClientInfo) GetProtoVersion() string {
	if m != nil {
		return m.ProtoVersion
	}
	return ""
}

func (m *ClientInfo) GetOSType() uint32 {
	if m != nil {
		return m.OSType
	}
	return 0
}

func (m *ClientInfo) GetOSVersion() string {
	if m != nil {
		return m.OSVersion
	}
	return ""
}

func (m *ClientInfo) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *ClientInfo) GetDeviceNumber() string {
	if m != nil {
		return m.DeviceNumber
	}
	return ""
}

type Session struct {
	ID     uint64      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Addr   string      `protobuf:"bytes,2,opt,name=Addr" json:"Addr,omitempty"`
	User   *UserInfo   `protobuf:"bytes,3,opt,name=User" json:"User,omitempty"`
	Client *ClientInfo `protobuf:"bytes,4,opt,name=Client" json:"Client,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Session) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Session) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Session) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Session) GetClient() *ClientInfo {
	if m != nil {
		return m.Client
	}
	return nil
}

type SessionResult struct {
	Data []*Session `protobuf:"bytes,3,rep,name=Data" json:"Data,omitempty"`
}

func (m *SessionResult) Reset()                    { *m = SessionResult{} }
func (m *SessionResult) String() string            { return proto.CompactTextString(m) }
func (*SessionResult) ProtoMessage()               {}
func (*SessionResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SessionResult) GetData() []*Session {
	if m != nil {
		return m.Data
	}
	return nil
}

type SessionStatRequest struct {
}

func (m *SessionStatRequest) Reset()                    { *m = SessionStatRequest{} }
func (m *SessionStatRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionStatRequest) ProtoMessage()               {}
func (*SessionStatRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type SessionStat struct {
	Count       int32            `protobuf:"varint,1,opt,name=Count" json:"Count,omitempty"`
	DomainUsers map[string]int32 `protobuf:"bytes,2,rep,name=DomainUsers" json:"DomainUsers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ConnNumbers map[uint64]int32 `protobuf:"bytes,3,rep,name=ConnNumbers" json:"ConnNumbers,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *SessionStat) Reset()                    { *m = SessionStat{} }
func (m *SessionStat) String() string            { return proto.CompactTextString(m) }
func (*SessionStat) ProtoMessage()               {}
func (*SessionStat) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *SessionStat) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SessionStat) GetDomainUsers() map[string]int32 {
	if m != nil {
		return m.DomainUsers
	}
	return nil
}

func (m *SessionStat) GetConnNumbers() map[uint64]int32 {
	if m != nil {
		return m.ConnNumbers
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "rpc.UserInfo")
	proto.RegisterType((*ClientInfo)(nil), "rpc.ClientInfo")
	proto.RegisterType((*Session)(nil), "rpc.Session")
	proto.RegisterType((*SessionResult)(nil), "rpc.SessionResult")
	proto.RegisterType((*SessionStatRequest)(nil), "rpc.SessionStatRequest")
	proto.RegisterType((*SessionStat)(nil), "rpc.SessionStat")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SessionStore service

type SessionStoreClient interface {
	Save(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error)
	Update(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error)
	Remove(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error)
	Replace(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error)
	Stat(ctx context.Context, in *SessionStatRequest, opts ...grpc.CallOption) (*SessionStat, error)
	Get(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error)
}

type sessionStoreClient struct {
	cc *grpc.ClientConn
}

func NewSessionStoreClient(cc *grpc.ClientConn) SessionStoreClient {
	return &sessionStoreClient{cc}
}

func (c *sessionStoreClient) Save(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error) {
	out := new(SessionResult)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStoreClient) Update(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error) {
	out := new(SessionResult)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStoreClient) Remove(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error) {
	out := new(SessionResult)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStoreClient) Replace(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error) {
	out := new(SessionResult)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Replace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStoreClient) Stat(ctx context.Context, in *SessionStatRequest, opts ...grpc.CallOption) (*SessionStat, error) {
	out := new(SessionStat)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Stat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStoreClient) Get(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResult, error) {
	out := new(SessionResult)
	err := grpc.Invoke(ctx, "/rpc.SessionStore/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SessionStore service

type SessionStoreServer interface {
	Save(context.Context, *Session) (*SessionResult, error)
	Update(context.Context, *Session) (*SessionResult, error)
	Remove(context.Context, *Session) (*SessionResult, error)
	Replace(context.Context, *Session) (*SessionResult, error)
	Stat(context.Context, *SessionStatRequest) (*SessionStat, error)
	Get(context.Context, *Session) (*SessionResult, error)
}

func RegisterSessionStoreServer(s *grpc.Server, srv SessionStoreServer) {
	s.RegisterService(&_SessionStore_serviceDesc, srv)
}

func _SessionStore_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Save(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Update(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStore_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Remove(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStore_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Replace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Replace(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Stat(ctx, req.(*SessionStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SessionStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStoreServer).Get(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.SessionStore",
	HandlerType: (*SessionStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _SessionStore_Save_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SessionStore_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SessionStore_Remove_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _SessionStore_Replace_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _SessionStore_Stat_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SessionStore_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/rpc/session.proto",
}

func init() { proto.RegisterFile("lib/rpc/session.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x8f, 0x12, 0x41,
	0x10, 0xdd, 0xf9, 0xe2, 0xa3, 0x00, 0x25, 0x95, 0x55, 0x27, 0x13, 0x63, 0xd8, 0x89, 0x89, 0x68,
	0x94, 0x55, 0xf6, 0xb2, 0xf1, 0x60, 0x62, 0x60, 0x63, 0x48, 0x0c, 0x6b, 0x9a, 0x5d, 0xef, 0xc3,
	0xd0, 0x9a, 0xc9, 0xc2, 0xcc, 0x38, 0xd3, 0x10, 0xf9, 0x07, 0xfe, 0x11, 0x8f, 0xfe, 0x41, 0x4f,
	0xa6, 0xab, 0x1b, 0x68, 0xf0, 0xb0, 0xdc, 0xa6, 0x5e, 0xd5, 0xab, 0xaa, 0x7e, 0xaf, 0x32, 0xf0,
	0x68, 0x9e, 0x4c, 0xcf, 0x8b, 0x3c, 0x3e, 0x2f, 0x79, 0x59, 0x26, 0x59, 0xda, 0xcb, 0x8b, 0x4c,
	0x64, 0xe8, 0x14, 0x79, 0x1c, 0xfe, 0xb2, 0xa0, 0x76, 0x5b, 0xf2, 0x62, 0x94, 0x7e, 0xcb, 0x10,
	0xc1, 0x1d, 0x47, 0x0b, 0xee, 0x5b, 0x1d, 0xab, 0x5b, 0x67, 0xf4, 0x8d, 0x8f, 0xa1, 0x32, 0xcc,
	0x16, 0x51, 0x92, 0xfa, 0x36, 0xa1, 0x3a, 0x22, 0x9c, 0xaf, 0x92, 0x98, 0xfb, 0x8e, 0xc6, 0x29,
	0xc2, 0x00, 0x6a, 0xe3, 0x24, 0xbe, 0xa3, 0x3e, 0x2e, 0x65, 0xb6, 0x31, 0x3e, 0x85, 0xfa, 0xe7,
	0xec, 0x7b, 0x92, 0xde, 0x24, 0x0b, 0xee, 0x7b, 0x1d, 0xab, 0xeb, 0xb2, 0x1d, 0x10, 0xfe, 0xb5,
	0x01, 0x06, 0xf3, 0x84, 0xa7, 0x82, 0x96, 0x79, 0x0b, 0xde, 0xd5, 0x4f, 0x51, 0x44, 0xbe, 0xd5,
	0x71, 0xba, 0x8d, 0x7e, 0xd0, 0x2b, 0xf2, 0xb8, 0xb7, 0xcb, 0xf7, 0x28, 0x79, 0x95, 0x8a, 0x62,
	0xcd, 0x54, 0x21, 0x3e, 0xdb, 0xf0, 0x6f, 0xd6, 0x39, 0xa7, 0x75, 0x5b, 0xcc, 0x40, 0xf0, 0x39,
	0xb4, 0x54, 0xf4, 0x95, 0x17, 0x52, 0x07, 0xbd, 0xf9, 0x3e, 0x28, 0x97, 0xfc, 0x22, 0xf5, 0xa1,
	0x26, 0xea, 0x05, 0x3b, 0x00, 0x43, 0x68, 0x52, 0xb0, 0x69, 0xe1, 0x51, 0xc1, 0x1e, 0x26, 0xa5,
	0xb9, 0x9e, 0x10, 0xbd, 0x42, 0x3b, 0xe8, 0x48, 0x76, 0xbe, 0x9e, 0x6c, 0x88, 0x55, 0xd5, 0x79,
	0x0b, 0xc8, 0xed, 0x95, 0x84, 0xc4, 0xac, 0x51, 0xda, 0x40, 0xe4, 0x64, 0x15, 0x8d, 0x97, 0x8b,
	0x29, 0x2f, 0xfc, 0xba, 0x9a, 0x6c, 0x62, 0xc1, 0x25, 0xc0, 0x4e, 0x16, 0x6c, 0x83, 0x73, 0xc7,
	0xd7, 0xda, 0x4d, 0xf9, 0x89, 0xa7, 0xe0, 0xad, 0xa2, 0xf9, 0x92, 0x6b, 0x2f, 0x55, 0xf0, 0xde,
	0xbe, 0xb4, 0xc2, 0x35, 0x54, 0x27, 0xea, 0x3a, 0xf0, 0x01, 0xd8, 0xa3, 0x21, 0xb1, 0x5c, 0x66,
	0x8f, 0x86, 0xf2, 0x2a, 0x3e, 0xce, 0x66, 0x85, 0xe6, 0xd0, 0x37, 0x9e, 0x81, 0x2b, 0xaf, 0x86,
	0x14, 0x6c, 0xf4, 0x5b, 0xe4, 0xcd, 0xe6, 0x8c, 0x18, 0xa5, 0xf0, 0x05, 0x54, 0x94, 0xb0, 0x24,
	0x62, 0xa3, 0xff, 0xf0, 0xc0, 0x40, 0xa6, 0xd3, 0xe1, 0x3b, 0x68, 0xe9, 0xd1, 0x8c, 0x97, 0xcb,
	0xb9, 0xc0, 0x0e, 0xb8, 0xc3, 0x48, 0x44, 0xbe, 0x43, 0xc6, 0x37, 0x89, 0xb7, 0xa9, 0xa0, 0x4c,
	0x78, 0x0a, 0xa8, 0x81, 0x89, 0x88, 0x04, 0xe3, 0x3f, 0x96, 0xbc, 0x14, 0xe1, 0x1f, 0x1b, 0x1a,
	0x06, 0x2c, 0x5f, 0x3b, 0xc8, 0x96, 0xa9, 0xa0, 0xb7, 0x78, 0x4c, 0x05, 0x38, 0x80, 0x86, 0x3a,
	0x61, 0xb9, 0x65, 0xe9, 0xdb, 0x34, 0xe4, 0xcc, 0x1c, 0x22, 0xc9, 0x3d, 0xa3, 0x46, 0x1d, 0x99,
	0xc9, 0x92, 0x4d, 0x06, 0x59, 0x9a, 0x2a, 0xd9, 0x4b, 0xbd, 0xe9, 0xff, 0x4d, 0x8c, 0x1a, 0xdd,
	0xc4, 0x40, 0x82, 0x0f, 0xd0, 0x3e, 0x9c, 0x72, 0x9f, 0x67, 0x9e, 0xe1, 0x99, 0xe4, 0x1f, 0x0e,
	0x30, 0xf9, 0xee, 0x3d, 0xfc, 0xfe, 0x6f, 0x1b, 0x9a, 0xdb, 0x6d, 0xb3, 0x82, 0xe3, 0x2b, 0x70,
	0x27, 0xd1, 0x8a, 0xe3, 0x9e, 0xe4, 0x01, 0xee, 0x19, 0x40, 0x16, 0x85, 0x27, 0xf8, 0x1a, 0x2a,
	0xb7, 0xf9, 0x2c, 0x12, 0x47, 0x57, 0x33, 0xbe, 0xc8, 0x8e, 0xec, 0xfd, 0x06, 0xaa, 0x8c, 0xe7,
	0xf3, 0x28, 0x3e, 0xae, 0xfc, 0x02, 0x5c, 0xf2, 0xfb, 0xc9, 0xa1, 0xfe, 0xfa, 0x30, 0x82, 0xf6,
	0x61, 0x22, 0x3c, 0xc1, 0x97, 0xe0, 0x7c, 0xe2, 0xe2, 0x98, 0xfe, 0xd3, 0x0a, 0xfd, 0x2f, 0x2f,
	0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x5a, 0x67, 0x57, 0x48, 0x05, 0x00, 0x00,
}
