// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/cluster.proto

/*
Package lib is a generated protocol buffer package.

It is generated from these files:
	lib/cluster.proto

It has these top-level messages:
	ServiceInfo
	ServerInfo
	RegisterReturn
*/
package lib

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
}

func (m *ServiceInfo) Reset()                    { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string            { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()               {}
func (*ServiceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ServerInfo struct {
	Type     string         `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	ID       uint32         `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	IP       string         `protobuf:"bytes,3,opt,name=IP" json:"IP,omitempty"`
	Port     int32          `protobuf:"varint,4,opt,name=Port" json:"Port,omitempty"`
	Services []*ServiceInfo `protobuf:"bytes,5,rep,name=Services" json:"Services,omitempty"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerInfo) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ServerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type RegisterReturn struct {
	ID          uint32        `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NewServers  []*ServerInfo `protobuf:"bytes,2,rep,name=NewServers" json:"NewServers,omitempty"`
	DownServers []*ServerInfo `protobuf:"bytes,3,rep,name=DownServers" json:"DownServers,omitempty"`
}

func (m *RegisterReturn) Reset()                    { *m = RegisterReturn{} }
func (m *RegisterReturn) String() string            { return proto.CompactTextString(m) }
func (*RegisterReturn) ProtoMessage()               {}
func (*RegisterReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReturn) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RegisterReturn) GetNewServers() []*ServerInfo {
	if m != nil {
		return m.NewServers
	}
	return nil
}

func (m *RegisterReturn) GetDownServers() []*ServerInfo {
	if m != nil {
		return m.DownServers
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceInfo)(nil), "lib.ServiceInfo")
	proto.RegisterType((*ServerInfo)(nil), "lib.ServerInfo")
	proto.RegisterType((*RegisterReturn)(nil), "lib.RegisterReturn")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	Register(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (Cluster_RegisterClient, error)
	Sync(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*RegisterReturn, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Register(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (Cluster_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cluster_serviceDesc.Streams[0], c.cc, "/lib.Cluster/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterRegisterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cluster_RegisterClient interface {
	Recv() (*RegisterReturn, error)
	grpc.ClientStream
}

type clusterRegisterClient struct {
	grpc.ClientStream
}

func (x *clusterRegisterClient) Recv() (*RegisterReturn, error) {
	m := new(RegisterReturn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) Sync(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*RegisterReturn, error) {
	out := new(RegisterReturn)
	err := grpc.Invoke(ctx, "/lib.Cluster/Sync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	Register(*ServerInfo, Cluster_RegisterServer) error
	Sync(context.Context, *ServerInfo) (*RegisterReturn, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterServer).Register(m, &clusterRegisterServer{stream})
}

type Cluster_RegisterServer interface {
	Send(*RegisterReturn) error
	grpc.ServerStream
}

type clusterRegisterServer struct {
	grpc.ServerStream
}

func (x *clusterRegisterServer) Send(m *RegisterReturn) error {
	return x.ServerStream.SendMsg(m)
}

func _Cluster_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lib.Cluster/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Sync(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lib.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Cluster_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Cluster_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lib/cluster.proto",
}

func init() { proto.RegisterFile("lib/cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x46, 0xb1, 0x93, 0xd2, 0x72, 0x11, 0x05, 0x8e, 0xc5, 0x62, 0x8a, 0x32, 0x65, 0x40, 0x29,
	0x14, 0x36, 0x46, 0xb2, 0x64, 0xa9, 0x22, 0x17, 0xb1, 0x93, 0xc8, 0x20, 0x4b, 0xc1, 0xae, 0x9c,
	0x94, 0xaa, 0x2b, 0xe2, 0x87, 0xa3, 0x5c, 0x9a, 0x28, 0x20, 0x06, 0xb6, 0x3b, 0xeb, 0x7b, 0x77,
	0xcf, 0x36, 0x5c, 0x54, 0xba, 0x58, 0x94, 0xd5, 0xb6, 0x6e, 0x94, 0x4b, 0x36, 0xce, 0x36, 0x16,
	0xbd, 0x4a, 0x17, 0xd1, 0x03, 0x04, 0x6b, 0xe5, 0x3e, 0x74, 0xa9, 0x32, 0xf3, 0x6a, 0x11, 0xc1,
	0x5f, 0xbd, 0xbc, 0x2b, 0xc1, 0x42, 0x16, 0x9f, 0x48, 0xaa, 0x51, 0xc0, 0xf4, 0x59, 0xb9, 0x5a,
	0x5b, 0x23, 0x78, 0xc8, 0xe2, 0x89, 0xec, 0xdb, 0xe8, 0x93, 0x01, 0xb4, 0xb4, 0x72, 0x3d, 0xfc,
	0xb4, 0xdf, 0x0c, 0x70, 0x5b, 0xe3, 0x1c, 0x78, 0x96, 0x12, 0x77, 0x2a, 0x79, 0x96, 0x52, 0x9f,
	0x0b, 0x8f, 0x12, 0x3c, 0xcb, 0x5b, 0x26, 0xb7, 0xae, 0x11, 0x3e, 0x4d, 0xa6, 0x1a, 0xaf, 0x61,
	0x76, 0x70, 0xaa, 0xc5, 0x24, 0xf4, 0xe2, 0x60, 0x79, 0x9e, 0x54, 0xba, 0x48, 0x46, 0xa2, 0x72,
	0x48, 0x44, 0x5f, 0x0c, 0xe6, 0x52, 0xbd, 0xe9, 0xf6, 0x66, 0x52, 0x35, 0x5b, 0x67, 0x0e, 0x4b,
	0xd9, 0xb0, 0x74, 0x01, 0xb0, 0x52, 0xbb, 0xce, 0xb4, 0x16, 0x9c, 0x46, 0x9e, 0x0d, 0x23, 0x3b,
	0x7b, 0x39, 0x8a, 0xe0, 0x2d, 0x04, 0xa9, 0xdd, 0x99, 0x9e, 0xf0, 0xfe, 0x26, 0xc6, 0x99, 0xa5,
	0x85, 0xe9, 0x63, 0xf7, 0xbc, 0x78, 0x0f, 0xb3, 0x5e, 0x08, 0x7f, 0x43, 0x57, 0x97, 0x74, 0xf0,
	0x53, 0x38, 0x3a, 0xba, 0x61, 0x98, 0x80, 0xbf, 0xde, 0x9b, 0xf2, 0xbf, 0x44, 0x71, 0x4c, 0xbf,
	0x78, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x41, 0xd3, 0x77, 0x7f, 0xda, 0x01, 0x00, 0x00,
}
